### ISSUE TITLE
增加IPv6功能

### ISSUE THREAD

**Issue by Lanlan13-14** [Zephyruso/zashboard#104]
希望可以添加在每个节点旁边显示是否支持ipv6的功能，支持的旁边就显示ipv6不支持的旁边就不显示

**Comment by Zephyruso** [comment]
目前的卡片大小感觉很难放得下啊

**Comment by Lanlan13-14** [comment]
> 目前的卡片大小感觉很难放得下啊

但如果只显示v6应该就可以放得下吧

**Comment by Zephyruso** [comment]
让我想想卡片怎么布局

**Comment by bjl101501** [comment]
> 让我想想卡片怎么布局

![image](https://github.com/user-attachments/assets/066455ff-6d1f-4ab3-8528-d8650587aa8c)
感觉在节点名称后面或者type那里加个这个就行

**Comment by Zephyruso** [comment]
> > 让我想想卡片怎么布局
> 
> ![image](https://private-user-images.githubusercontent.com/82082262/397993534-066455ff-6d1f-4ab3-8528-d8650587aa8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODMzMTksIm5iZiI6MTczNDg4MzAxOSwicGF0aCI6Ii84MjA4MjI2Mi8zOTc5OTM1MzQtMDY2NDU1ZmYtNmQxZi00YWIzLTg1MjgtZDg2NTA1ODdhYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE1NTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNWIzYzA0NzU2MzgyMmIzNTIzM2ZkZjdmMWJmZDgxMDgzNTkxYjU5ZjlkNGJjMWI3MGU0MmIyYzYyM2RjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NFPe0gKpWsnglJcZDXAmNxdb0zh-c57D09e1rgoC0Pg) 感觉在节点名称后面或者type那里加个这个就行

感觉有点过于抽象了，之前手机端把udp缩写成了u被人提过bug，这个单写个6估计也会有很多人不理解

**Comment by bjl101501** [comment]
> > > 让我想想卡片怎么布局
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/82082262/397993534-066455ff-6d1f-4ab3-8528-d8650587aa8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODMzMTksIm5iZiI6MTczNDg4MzAxOSwicGF0aCI6Ii84MjA4MjI2Mi8zOTc5OTM1MzQtMDY2NDU1ZmYtNmQxZi00YWIzLTg1MjgtZDg2NTA1ODdhYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE1NTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNWIzYzA0NzU2MzgyMmIzNTIzM2ZkZjdmMWJmZDgxMDgzNTkxYjU5ZjlkNGJjMWI3MGU0MmIyYzYyM2RjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NFPe0gKpWsnglJcZDXAmNxdb0zh-c57D09e1rgoC0Pg) 感觉在节点名称后面或者type那里加个这个就行
> 
> 感觉有点过于抽象了，之前手机端把udp缩写成了u被人提过bug，这个单写个6估计也会有很多人不理解

那就只能把方框弄大一点，分两行，类似yacd那样

**Comment by Zephyruso** [comment]
先加上了，默认是关闭的，看看将来有什么好的展示方式的时候再默认打开

**Comment by Lanlan13-14** [comment]
Thanks

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lanlan13-14** [comment]
感谢啦

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Zephyruso** [comment]
> 1.31.0 singbox ios16.4 连接页面空的,清理缓存，无痕模式都不行，降级到1.30可以 ![IMG_1750](https://private-user-images.githubusercontent.com/28676500/398370109-2df42fc3-ad3c-4a83-9210-5257cb47fca9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzEzMjgsIm5iZiI6MTczNTAzMTAyOCwicGF0aCI6Ii8yODY3NjUwMC8zOTgzNzAxMDktMmRmNDJmYzMtYWQzYy00YTgzLTkyMTAtNTI1N2NiNDdmY2E5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA5MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNzhjNjEzZDlkNTMzODBmYzg5NGE1YmI1Yjg2MTVhMGQxMThhM2Y3MDYyN2FkMjkwOTQyOGQ0ZTdjNWQzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TOPCTflrkn1ETB28Rfaw2ZY6FI-_cZqbxEzmzjocqMA)

我这本地好的，你可以另开一个issue，附上你设置中后端的截图看看是不是自动切换到了其他后端，这个issue留给想讨论IPv6的人

**Comment by Zephyruso** [comment]
新版卡片的IPv6显示感觉可以了，这个issue先关了
