### ISSUE TITLE
2 Mb -> 9 Mb

### ISSUE THREAD

**Issue by fildunsky** [Zephyruso/zashboard#105]
1.31.0 became so fat! Could you please make it weight 2 Mb back again? It was so nice that it was very light before.

**Comment by Zephyruso** [comment]
The release contains two types of packages: dist.zip (https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip) and dist-cdn-fonts.zip (https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip). The dist-cdn-fonts.zip package is more friendly to devices with limited storage space, while the dist.zip package provides a better font loading experience.

**Comment by fildunsky** [comment]
Oh, thank you for clearing this out to me! Appreciate your work! Awesome panel!
