### ISSUE TITLE
连接页面为空

### ISSUE THREAD

**Issue by qwer123wd** [Zephyruso/zashboard#106]
1.31.0 singbox ios16.4，openclash ios16.4 连接页面空的,清理缓存，无痕模式都不行，降级到1.30可以 
使用 dist-cdn-fonts.zip https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip
![IMG_1751](https://github.com/user-attachments/assets/3cc67f2c-61bf-438b-81dc-680cef1f9662)
![IMG_1752](https://github.com/user-attachments/assets/7b6a314c-0adc-4e52-aaa9-562ad3086908)
![IMG_1753](https://github.com/user-attachments/assets/f8e0f2d8-a70c-473a-a20b-fddd7a8ee934)

**Comment by Zephyruso** [comment]
日志页面能看到连接刷日志吗

**Comment by Zephyruso** [comment]
我本地没有复现，不过我猜测了一下原因你试试最新的https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip 有没有好
