### ISSUE TITLE
Add "Close All Connections" Button

### ISSUE THREAD

**Issue by chami2000** [Zephyruso/zashboard#114]
Hi,
Can you add a "Close All Connections" button at the top of the connections list? It would make it easier to terminate multiple connections quickly.

Thanks!

![image](https://github.com/user-attachments/assets/b9a0f63a-64e2-4a4a-9010-426e004812a9)

**Comment by Zephyruso** [comment]
![image](https://github.com/user-attachments/assets/9c5ca9b0-ae77-4bd9-90ac-66912b360025)

This X button will close all connections

**Comment by chami2000** [comment]
Thanks for the clarification! I apologize for not noticing that the X button already performs that function. I appreciate your help
