### ISSUE TITLE
能否将延迟测试按钮调大一点

### ISSUE THREAD

**Issue by elliot-zhao** [Zephyruso/zashboard#116]
![image](https://github.com/user-attachments/assets/a9bde693-8c05-4480-9cb9-29b23d699637)
这个延迟测试按钮有点小，再加上底色和背景的颜色没有做区分。导致在点击的时候不方便定位。如果点击到外面，会导致整个策略组被展开和关闭。能否在外面加个框方便定位？
正在测试的时候的颜色闪烁也有点看不出来，不知道是否正在做延迟测试。能否在测试的时候换成类似省略号的图标（或其他不是延迟数字和闪电的图标）表示正在进行延迟测试更可观？
![image](https://github.com/user-attachments/assets/b93febb3-fa86-4eec-8d6f-a3a20f8a84f8)

请大佬根据实际情况酌情修改，感谢！

**Comment by Zephyruso** [comment]
你试试有没有好一点

**Comment by elliot-zhao** [comment]
大佬厉害，这下点不错了！
