### ISSUE TITLE
节点按延迟排序功能体验反馈

### ISSUE THREAD

**Issue by everstu** [Zephyruso/zashboard#118]
首先，感谢大佬提供好用的软件。

我来提交一下体验报告
目前发现一个体验上的问题：
节点按延迟排序是所有都会按延迟排序。对于某些selector不太友好。

原序：
![image](https://github.com/user-attachments/assets/a238a825-78fd-4b54-be77-6e3b10078ca3)

Zash 延迟排序:
![image](https://github.com/user-attachments/assets/33da8c52-c1f9-470f-8c5a-a64f0bbc9e2e)

Yacd Meta 延迟排序:
![image](https://github.com/user-attachments/assets/f4666843-a743-47d9-8572-10640bb3a5e9)

我觉着Yacd Meta这种更符合人体工程学，大佬参考参考。

最后再次感谢大佬提供好用的软件，谢谢!

**Comment by Zephyruso** [comment]
意思是想要只有节点排序，节点组的顺序不动？那节点和节点组的混合的该怎么排

**Comment by everstu** [comment]
是这个意思，我也不知道yacd meta是怎么实现这样的。

因为那个youtube组也排序就很会奇怪的。

**Comment by Zephyruso** [comment]
你试试现在的在线面板

**Comment by everstu** [comment]
配置文件：
![image](https://github.com/user-attachments/assets/4d166862-bed5-4bec-801c-63baedcb439e)

Yacd 排序表现：
![image](https://github.com/user-attachments/assets/27b6bc9d-6bc1-41df-bea2-87f34755eb9b)

**Comment by everstu** [comment]
> 你试试现在的在线面板

好滴。

**Comment by everstu** [comment]
是这个意思，大佬牛逼。

在线面板表现：
![image](https://github.com/user-attachments/assets/9a05d5bc-727c-4422-8db7-8481f49e158a)

另外还有一些小问题
- 1.setup入参的时候传入了http://或https://就会配置失败，这个可以做个正则匹配开头是http://或https://吗？做个参数兼容的意思。
- 2. 如果入参路径不是/#/setup，入参不会消失
入参路径非/#/setup，后面参数不会消失
![image](https://github.com/user-attachments/assets/0529add1-ac7c-46a2-ad7a-2a2744fa2fc1)

**Comment by Zephyruso** [comment]
> 1. setup入参的时候传入了 `http://` 或 `https://` 就会配置失败，这个可以做个正则匹配开头是 `http://` 或 `https://` 吗？做个参数兼容的意思

这种应该去找路径的提供者修复错误而不是面板兼容错误参数

> 2\. 如果入参路径不是/#/setup，入参不会消失

同样不是很理解路径提供者为什么要跳proxies而不是setup

**Comment by everstu** [comment]
> > 1. setup入参的时候传入了 `http://` 或 `https://` 就会配置失败，这个可以做个正则匹配开头是 `http://` 或 `https://` 吗？做个参数兼容的意思
> 
> 这种应该去找路径的提供者修复错误而不是面板兼容错误参数
> 
> > 2. 如果入参路径不是/#/setup，入参不会消失
> 
> 同样不是很理解路径提供者为什么要跳proxies而不是setup

嗯嗯，确实是这么回事，目前使用良好，谢谢大佬！

**Comment by Zephyruso** [comment]
> 1. setup入参的时候传入了 `http://` 或 `https://` 就会配置失败，这个可以做个正则匹配开头是 `http://` 或 `https://` 吗？做个参数兼容的意思。
> * 2. 如果入参路径不是/#/setup，入参不会消失
>      入参路径非/#/setup，后面参数不会消失

readme中更新了入参格式，你可以反馈给你的路径提供者参考

**Comment by everstu** [comment]
> > 1. setup入参的时候传入了 `http://` 或 `https://` 就会配置失败，这个可以做个正则匹配开头是 `http://` 或 `https://` 吗？做个参数兼容的意思。
> > 
> > 
> > * 2. 如果入参路径不是/#/setup，入参不会消失
> >      入参路径非/#/setup，后面参数不会消失
> 
> readme中更新了入参格式，你可以反馈给你的路径提供者参考

好滴，感谢大佬~
