### ISSUE TITLE
[Feature]想要个ip和网站连通性检查

### ISSUE THREAD

**Issue by bjl101501** [Zephyruso/zashboard#123]
不知道能不能行

> 通过 <iframe /> 加载 Embed 版本的 ip.skk.moe 到你的应用中：
> ```
> <iframe src="https://ip.skk.moe/simple" style="width: 100%; border: 0"></iframe>
> 
> <iframe src="https://ip.skk.moe/simple-dark" style="width: 100%; border: 0"></iframe>
> ```

**Comment by Zephyruso** [comment]
应该可行，不过样式怎么统一是个问题，我回头研究研究

**Comment by Zephyruso** [comment]
在设置页简单实现了个IP检查，网站连通性有空了我再看看

**Comment by Zephyruso** [comment]
连通性也放进设置页面里了，放侧边栏的话有些页面的侧边栏就太长了，不过目前设置页面页太长了，考虑拆分一下

**Comment by qianyiqq** [comment]
> 连通性也放进设置页面里了，放侧边栏的话有些页面的侧边栏就太长了，不过目前设置页面页太长了，考虑拆分一下

网络联通性能不能加个cloudflare,chatgpt，这两个应该用的会比较多

**Comment by qianyiqq** [comment]
还有我用cf节点，全球ip检测的还是cn的ip地址

**Comment by Zephyruso** [comment]
是可以考虑 但是这个并不能检测是否解锁，只是单纯的连通性检测

**Comment by Zephyruso** [comment]
> 网络联通性能不能加个cloudflare,chatgpt

是可以考虑 但是这个并不能检测是否解锁，只是单纯的连通性检测

**Comment by Zephyruso** [comment]
> 全球ip

将api.ip.sb走代理

**Comment by qianyiqq** [comment]
> > 全球ip
> 
> 将api.ip.sb走代理

这个检测不是很准，比如ipv6节点，cf节点都不准的，可以试试这个https://www.cloudflare.com/cdn-cgi/trace    https://api.ipify.org

**Comment by qianyiqq** [comment]
我写的脚本是通过这两个api获取ip然后放ip-api查询ip信息

**Comment by qianyiqq** [comment]
> > > 全球ip
> > 
> > 
> > 将api.ip.sb走代理
> 
> 这个检测不是很准，比如ipv6节点，cf节点都不准的，可以试试这个https://www.cloudflare.com/cdn-cgi/trace https://api.ipify.org

![IMG_20241229_165210](https://github.com/user-attachments/assets/423de868-95cd-46ff-ae36-f25e04688baf)

**Comment by Zephyruso** [comment]
> https://www.cloudflare.com/cdn-cgi/trace https://api.ipify.org

前者不支持跨域调用无法在面板中使用，后者只有单纯的ip信息没有asn以及国家等信息

**Comment by qianyiqq** [comment]
> > https://www.cloudflare.com/cdn-cgi/trace https://api.ipify.org
> 
> 前者不支持跨域调用无法在面板中使用，后者只有单纯的ip信息没有asn以及国家等信息

那就算了，我也看的不多，偶尔需要用自己搞得脚本就行

**Comment by qianyiqq** [comment]
> > https://www.cloudflare.com/cdn-cgi/trace https://api.ipify.org
> 
> 前者不支持跨域调用无法在面板中使用，后者只有单纯的ip信息没有asn以及国家等信息

https://ping0.cc/geo
试试这个，这个说实话也很不错，信息都有

**Comment by Zephyruso** [comment]
> https://ping0.cc/geo

这个只有纯文本的没有json格式，不太想解析纯文本

**Comment by ralopa673** [comment]
> > 连通性也放进设置页面里了，放侧边栏的话有些页面的侧边栏就太长了，不过目前设置页面页太长了，考虑拆分一下
> 
> 网络联通性能不能加个cloudflare,chatgpt，这两个应该用的会比较多

chatGPT的ping，可能是最没有参考价值的！

你能ping到的chatgpt，只是它挂在cloudflare CDN上的静态网页，根本不代表实际数据在 你↔️算力服务器 的往返延迟。

而CDN部署的地理区位太复杂了，导致这个结果可能非常有误导性。

- 例如，你用🇯🇵、🇸🇬节点，发现你↔️chatgpt CDN的延迟都是70ms，会误导你 **天真的认为** 两个节点都是一样快。但实际上，根本就不是！ 
- 日本到美国东部大约90～110ms，新加坡到美国东部大约170～190ms
- 再加🇺🇸东部→🇺🇸俄亥俄州的RTT延迟，以Cleveland为例，这一段至少需要59ms延迟。
- 最后，这两个节点，表面上均为70ms、70ms；但实际上，各自至少来到230～250ms、299～319ms

除非，你能：1️⃣ 精确找出 Openai算力服务器的ip地址，或者2️⃣ 把这些延迟都加起来，用条件句➕跨区延迟进行估算。

**Comment by eric-gitta-moore** [comment]
还挺需要一个类似 clash verge rev 的解锁测试，这个可以行吗

<img width="2109" height="1441" alt="Image" src="https://github.com/user-attachments/assets/fd815bda-2809-48b9-9615-27a8eba13a9c" />

https://github.com/clash-verge-rev/clash-verge-rev/blob/4a7859bdae3adf4b395630e3518f916a0a54b09d/src-tauri/src/cmd/media_unlock_checker/mod.rs#L43

https://github.com/clash-verge-rev/clash-verge-rev/blob/4a7859bdae3adf4b395630e3518f916a0a54b09d/src/pages/unlock.tsx#L259

**Comment by Zephyruso** [comment]
不可行 有跨域限制
