### ISSUE TITLE
[建议]connections 页面的表格列能够固定

### ISSUE THREAD

**Issue by DustinWin** [Zephyruso/zashboard#126]
地址：https://board.zash.run.place/#/connections
说明：
当 connections 页面内连接数较多时，下拉后希望表格列能够固定而不是一并被拉到上面而遮盖
![QQ20241229-163115](https://github.com/user-attachments/assets/054af8cc-07f9-4a9e-8ef7-4f94972dd90e)

**Comment by Zephyruso** [comment]
加上了
