### ISSUE TITLE
openai的ping,可能要加上openai CDN标注。它算力服务器只在（🇺🇸东）俄亥俄州部署

### ISSUE THREAD

**Issue by ralopa673** [Zephyruso/zashboard#127]
zash面板越来越完美了。

不过，OpenAI的ping，实际上只是对CDN的ping，这些CDN只储存网页css、js等静态文件，以及负责回传🇺🇸俄亥俄州的算力服务器→CDN→用户端的数据，**而不参与计算过程**。

但YouTube、GitHub不一样，它们在🇯🇵东京、🇸🇬新加坡、🇰🇷首尔、🇭🇰的CDN是储存了它们_主要业务_的音视频文件。

所以，OpenAI的ping，性质和它们是大相径庭的。

建议OpenAI加个“CDN”，或“静态网页”，或者其他什么能够避免误导的标注。

**Comment by Zephyruso** [comment]
感谢提醒！已更正
