### ISSUE TITLE
礼貌求问是否可以增加显示功能

### ISSUE THREAD

**Issue by qljsyph** [Zephyruso/zashboard#130]
z佬冒昧问一句面板会加白天模式和夜间模式随系统时间进行切换的功能么，要是有人问过或认为没有必要，我自行closed

**Comment by Zephyruso** [comment]
设置中theme里的default就是啊

**Comment by Zephyruso** [comment]
改了个名，把default改名为了自动切换

**Comment by qljsyph** [comment]
> 改了个名，将默认改名为自动切换

谢谢z佬，我理解有误了，感谢感谢。面板越来越棒，更新辛苦了。
