### ISSUE TITLE
卡片模式下排序

### ISSUE THREAD

**Issue by qwer123wd** [Zephyruso/zashboard#134]
卡片模式下点击关闭按钮会打开信息窗口，
<img width="47" alt="截屏2024-12-31 10 59 39" src="https://github.com/user-attachments/assets/13af81ff-26c1-4f5a-a0b3-2c7e8a3afef3" />
卡片模式下的连接类别能不能像表格模式一样支持升序/降序排列吗
<img width="80" alt="截屏2024-12-31 11 01 13" src="https://github.com/user-attachments/assets/21a1e823-9e21-40a5-b0b0-7a1c70b5f3e6" />

**Comment by Zephyruso** [comment]
关闭修了 不过发版工具被我玩砸了一会修好了再发fix

**Comment by Zephyruso** [comment]
> 支持升序/降序排列

这个会考虑在未来的几个版本支持

**Comment by Zephyruso** [comment]
加上了
