### ISSUE TITLE
使用内置页面会往上拉

### ISSUE THREAD

**Issue by Auroraxpm** [Zephyruso/zashboard#137]
https://github.com/user-attachments/assets/cce33e57-7cd8-4d48-a567-a4d5630717a0

从136版本开始

**Comment by Zephyruso** [comment]
这是嵌了个iframe是吗，我还是头一次见这么用的，你这个插件从哪下的我去研究研究

**Comment by Auroraxpm** [comment]
https://github.com/Thaolga/openwrt-nekobox/releases

**Comment by Zephyruso** [comment]
从1.36开始是指1.36就是坏的还是1.37

**Comment by Auroraxpm** [comment]
136是正常的

**Comment by Auroraxpm** [comment]
可以了谢谢

**Comment by Zephyruso** [comment]
啊不是我还啥都没改呢咋好的

**Comment by Auroraxpm** [comment]
页面的还是会上拉 主菜单的正常了

**Comment by Zephyruso** [comment]
试试现在的gh-pages分支会不会好

**Comment by Auroraxpm** [comment]
正常了 感谢
