### ISSUE TITLE
overlapping text in the rules section

### ISSUE THREAD

**Issue by inipew** [Zephyruso/zashboard#23]
I think this is also my fault for displaying dns.rules, what is drawn is not all options in dns.rules because there are still other options that are not used.🗿
![image](https://github.com/user-attachments/assets/c40001b3-976c-46e2-90c7-87e791e2036d)

**Comment by Zephyruso** [comment]
I have fixed it, Give it a try

**Comment by inipew** [comment]
> I have fixed it, Give it a try

nice, thank you
![image](https://github.com/user-attachments/assets/18561e49-ba54-4c69-a544-775a2cb193bb)
