### ISSUE TITLE
[REQ] Two Columns Proxies for Mobile Layout

### ISSUE THREAD

**Issue by JeelsBoobz** [Zephyruso/zashboard#27]
Proxy list is too wide in mobile version
![Screenshot_2024-12-01-18-30-10-902_com kiwibrowser browser](https://github.com/user-attachments/assets/ab38dab4-e587-4300-a4c9-64bd07a925b1)

**Comment by Zephyruso** [comment]
What is the resolution of your screen?

**Comment by Zephyruso** [comment]
I have made a config for large mobile screen like yours, Give it a try
