### ISSUE TITLE
还没有切换 全局/规则/直连 的选项。

### ISSUE THREAD

**Issue by Remonli** [Zephyruso/zashboard#49]
试了一下，好像还没有按钮可以切换 全局/规则/直连。

另外能不能把编译后的gh-pages打包一起发布一下？下载到本地方便一点。

**Comment by Zephyruso** [comment]
切换在代理页面的控制组件里
![image](https://github.com/user-attachments/assets/f9add48e-97b6-4d9c-9936-a239fdf5efc0)
gh-pages在release中有，或者可以通过 https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip 直接下载

**Comment by Remonli** [comment]
额，我隐藏了边栏，怪不得看不到。

release只看到src包，没有看见有编译好的网页呀。

**Comment by Zephyruso** [comment]
隐藏了边栏之后在页面内上方
![image](https://github.com/user-attachments/assets/5b92fdbe-47ef-422d-a85a-62f7d80bc242)

啊 确实，那通过上面的链接下载就好，那个链接永远指向的是最新的gh-pages

**Comment by Zephyruso** [comment]
折腾了一下actions，现在发版的时候会带上编译好的dist.zip了

**Comment by Remonli** [comment]
嗯，这样方便一点。用github那个打包zip下载，有时候会出问题。
