### ISSUE TITLE
[Feature request] Add version tags to the repo

### ISSUE THREAD

**Issue by muink** [Zephyruso/zashboard#6]
FullCombo Mihomo's dashboard checker relies on the `Releases version` or `Tags` of the dashboard repository.
And I added zashboard to my project https://github.com/muink/openwrt-fchomo/commit/6f7509cb2f1742192582795ee447365d3318533b but for it to work properly, it requires you to push the version tag after every new release.

**Comment by Zephyruso** [comment]
OK i will do it

**Comment by muink** [comment]
Thank you, it's working.
