### ISSUE TITLE
本地面板更新错误

### ISSUE THREAD

**Issue by qianyiqq** [Zephyruso/zashboard#64]
使用1.19.0本地面板，点击更新面板后，升级成METACUBEXD了.....,是不是面板更新的url地址没改

**Comment by Zephyruso** [comment]
更新面板是由调用api完成的，你的mihomo的配置文件中url的链接是否没填或者填写的metacubexd，请填写为 https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip

**Comment by qianyiqq** [comment]
我把这条给删了没注意到，多谢提醒，改过后可以了

**Comment by Zephyruso** [comment]
> 有一个设计上的建议，不要存储所有设置，只存储修改过的设置，不存储没改过的设置 这样便于以后更改默认设置，也会减少bug
> 
> @Zephyruso

这是一个好建议
