### ISSUE TITLE
移动端日志页面信息卡片遮挡滚动条

### ISSUE THREAD

**Issue by yorunning** [Zephyruso/zashboard#81]
见下图，代理、连接、设置页显示正常。
面板版本1.26
![image](https://github.com/user-attachments/assets/61aafc75-741a-42ac-8b6e-cce207787ebb)
![image](https://github.com/user-attachments/assets/cbb1bbef-9c7a-44d8-a468-f19f6c99bffa)

**Comment by Zephyruso** [comment]
移动端感觉滚动条没什么必要 都隐藏了直接 你再试试

**Comment by Zephyruso** [comment]
用了一下感觉好像还是有点必要于是老老实实的把阴影修了
