### ISSUE TITLE
safari的网页不安全内容无法设置

### ISSUE THREAD

**Issue by laozhang123456** [Zephyruso/zashboard#87]

**Comment by Zephyruso** [comment]
那只能用mihomo https://wiki.metacubex.one/config/general/#_9 /sing-box https://sing-box.sagernet.org/configuration/experimental/clash-api/#external_ui_download_url 自带的UI服务器功能来部署一个本地的面板了， 我暂时没有域名，无法解除在线面板的https

**Comment by laozhang123456** [comment]
谢谢，本地已部署--完美，egde和chrome也没问题。

**Comment by laozhang123456** [comment]
有个长期免费的域名注册，不打算公开（担心和eu.org下场一样），我发你邮箱吧！

**Comment by Zephyruso** [comment]
感谢感谢，目前域名主要有其他方面的顾虑，等这些解决了应该会添加的

**Comment by laozhang123456** [comment]
明白了，您太客气了，柷项目大火！

Zephyruso ***@***.***> 于 2024年12月14日周六 下午12:10写道：
